### ISSUE TITLE
Add new QC rules for QOL/PROMIS survey

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/qaqc_testing#112]
Please add to the QC checks for the QOL/PROMIS survey the following rules:

- QC check for consistency between the survey completion flag and started/submitted dates like we have for other surveys
- QC check for 'not eligible' survey completion status based on the conditionality in the notification first contact attempt. (as the survey is triggered to participants upon the first notification being sent to the participant to complete the survey - where they are 90-days post verification and not withdrawn or deceased. Anyone in the 'not eligible' status should not meet the criteria to have the notification sent)

@HanaShiho please add full list of conditionality for first contact attempt

**Comment by HanaShiho** [comment]
Conditions to get the 1st message 

- Participant is verified AND
- Has not withdrawn consent AND
- Has not refused all future activities AND
- Has not refused all future surveys AND
- Is not deceased AND
- greater or equal 90 days post verification (to exclude the backlog pts)

Concept IDs 
821247024 = 197316935 AND 
747006172 = 104430631 AND 
906417725= 104430631 AND             
685002411_867203506 = 104430631 AND
987563196 = 104430631 AND                    
914594314 >=  2023-12-01T04:00:00.000Z (programmed to send to pts verified on or after 12/01/23)

**Comment by jacobmpeters** [comment]
Thanks for the note @robertsamm and for the details @HanaShiho.

@KELSEYDOWLING7 and I chatted about these two rules. They don't fit well within the constraints of the generic QC report because the first one requires conditionality where its after a date or x amount of days after a date and the second one requires more than 4 cross-validations.

Kelsey plans to code them as custom QC metrics.
