### ISSUE TITLE
Campaign type rule is failing to flag some participants

### ISSUE THREAD

**Issue by jacobmpeters** [Analyticsphere/qaqc_testing#26]
Issue reported by @mnataraj92 on MS Teams:

The rule on line 168 regarding campaign type says "Campaign Type (667474224) should not be missing for any active recruits (512820379 = 486306141) and for any verified passive recruits (512820379 = 854703046 and 821247024 = 197316935)" but I don't think the report caught 4 active recruits missing campaign type that should have it.

**Comment by jacobmpeters** [comment]
These are the Connect_IDs that should be flagged by this rule but are not:

- 1268440754
- 4395364571
- 7504116990
- 7651898410

**Comment by jacobmpeters** [comment]
@mnataraj92 I looked into these Connect_IDs in BQ:

``SELECT Connect_ID, state_d_667474224, d_512820379,d_821247024 FROM `nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP` WHERE Connect_ID IN ("1268440754", "4395364571", "7504116990", "7651898410")``

The rules at 168 and 169 are NA or crossValid1/2 rules in [qc_rules_recruitment.xlsx](https://nih.box.com/s/fjn2hpbks62lerc60vod7ngn187334a9). Should they be changed to simple crossValid rules? This would flag Connect_IDs 1268440754 and 7651898410 because they have state_d_667474224=NULL. This would not flag 4395364571 and 7504116990 which have state_d_667474224=926338735 which is listed as a valid value in both Rules.

**Comment by mnataraj92** [comment]
Hi @jacobmpeters, could we please slightly change this rule again? The report caught all of the active recruits missing campaign type + passive verified recruits missing campaign type after changing them to simple crossValid rules which is great! But Michelle asked to make it so that: 

All active recruits (except active duplicates) should have campaign type, and all passive verified participants should have campaign type. (So the rule would flag those where campaign type is null for active recruits (except active duplicates) and for passive verified recruits). 

So the rule would be:
"Campaign Type (667474224) should not be missing for any active recruits with a verification status of not yet verified, verified, cannot be verified, or outreach timed out  (512820379 = 486306141 and 821247024 = 875007964, 197316935, 219863910, or 160161595) and for any verified passive recruits (512820379 = 854703046 and 821247024 = 197316935)"

We still want the rule to capture where campaign type = null for active recruits that have the above verification statuses or for passive verified participants. Nothing needs to change in the portion of the rule dealing with the verified passive recruits.

Thank you!

**Comment by jacobmpeters** [comment]
Hi Madhuri, 

I adjusted these rules at lines 168 and 169 in [qc_rules_recruitment.xlsx](https://nih.box.com/s/fjn2hpbks62lerc60vod7ngn187334a9). They now read as follows:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/petersjm/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/petersjm/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Label | ConceptID | Qctype | ValidValues | CrossVariableConceptID1 | CrossVariableConceptID1Value | CrossVariableConceptID2 | CrossVariableConceptID2Value
-- | -- | -- | -- | -- | -- | -- | --
Campaign   Type | state_d_667474224 | NA or crossValid2 | 926338735, 348281054, 324692899,   351257378, 647148178, 834544960, 682916147, 153365143, 663706936, 181769837,   398561594 | d_512820379 | 486306141 | d_821247024 | 875007964, 197316935, 219863910,   160161595
Campaign   Type | state_d_667474224 | NA or crossValid2 | 926338735, 348281054, 324692899,   351257378, 647148178, 834544960, 682916147, 153365143, 663706936, 181769837,   398561594 | d_512820379 | 854703046 | d_821247024 | 197316935



</body>

</html>

I will try to incorporate the updates in this weeks run, but I will let you know.

**Comment by jacobmpeters** [comment]
@mnataraj92 Is this issue resolved? If so, can we close it?

**Comment by mnataraj92** [comment]
yep we can close this!
